services:
  oracle-itp:
    image: oracle/database:19.3.0-ee
    container_name: oracle-itp
    ports:
      - "1521:1521"
    environment:
      ORACLE_PWD: Oracle@168
      ENABLE_ARCHIVELOG: true
    volumes:
      - oracle_data_itp:/opt/oracle/oradata
    networks:
      - itp-net

volumes:
  oracle_data_itp:

networks:
  itp-net:
    external: true
