server:
  port: 9991
spring:
  application:
    name: admin-bff


  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888


  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: adminbff
              uri: http://localhost:3001
              predicates:
                - Path=/**
              filters:
                - TokenRelay=

  security:
    oauth2:
      client:
        provider:
          itp-adminbff:
            issuer-uri: http://localhost:9090
        registration:
          itp-adminbff:
            provider: itp-adminbff
            client-id: itp-adminbff
            client-secret: qwerqwer
            redirect-uri: http://localhost:9991/login/oauth2/code/itp-adminbff
            authorization-grant-type:
              - authorization_code
            scope:
              - openid # Auto issue access token
              - profile # Get profile
              - email # Get email
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090
