server:
  port: 20262
spring:
  application:
    name: pipeline

  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888


  security:
    oauth2:
      client:
        provider:
          itp-standard:
            issuer-uri: http://localhost:9090
        registration:
          itp-standard:
            provider: itp-standard
            client-id: itp-standard
            client-secret: qwerqwer
            redirect-uri: http://localhost:9999/login/oauth2/code/itp-standard
            authorization-grant-type: client_credentials
#              - authorization_code
#              - client_credentials
            scope:
              - openid # Auto issue access token
              - profile # Get profile
              - email # Get email
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090

# Resilience4j
#resilience4j:
#  circuitbreaker:
#    configs:
#      default:
#        sliding-window-size: 10 # Number of requests
#        failure-rate-threshold: 50 # Percentage of 50%
#        permitted-number-of-calls-in-half-open-state: 2 # Number of requests before change ot half-open
#        wait-duration-in-open-state: 10000
#    instances:
#      accountService:
#        base-config: default

# Actuator (add this if not present)
management:
  endpoints:
    web:
      exposure:
        include: "*"
#  health:
#    circuitbreakers:
#      enabled: true
logging:
  level:
    co.istad.dara.pipeline_service: DEBUG